# Generated by Django 6.0.5 on 2026-05-22 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TODO", "0008_alter_taskdetails_priority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskdetails",
            name="Priority",
            field=models.CharField(
                choices=[("L", "Low"), ("H", "high"), ("M", "Medium")],
                default="M",
                max_length=1,
            ),
        ),
    ]
