# Generated by Django 6.0.5 on 2026-05-23 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TODO", "0013_alter_taskdetails_priority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskdetails",
            name="Priority",
            field=models.CharField(
                choices=[("M", "Medium"), ("H", "high"), ("L", "Low")],
                default="M",
                max_length=1,
            ),
        ),
    ]
