# Generated by Django 6.0.5 on 2026-05-21 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Recipes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Title", models.TextField(max_length=100)),
                ("Description", models.TextField()),
                ("Prep_time", models.IntegerField()),
                (
                    "Category",
                    models.TextField(
                        choices=[
                            ("Br", "Breakfast"),
                            ("Lh", "Lunch"),
                            ("Dr", "Dinner"),
                        ],
                        default="Br",
                    ),
                ),
                ("Recipe_Photo", models.ImageField(upload_to="")),
                ("Instruction", models.TextField()),
                ("Recipe_Calories", models.IntegerField()),
                ("Recipe_Protein", models.IntegerField()),
                ("Recipe_Carbs", models.IntegerField()),
                ("Recipe_Fats", models.IntegerField()),
                (
                    "Person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
