# Generated by Django 6.0.5 on 2026-05-22 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Recipe_Meal_Planner", "0002_ingredients"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ingredients",
            name="Recipe",
        ),
        migrations.AlterField(
            model_name="recipes",
            name="Recipe_Photo",
            field=models.ImageField(upload_to="Recipes/Photo"),
        ),
        migrations.CreateModel(
            name="Recipe_Bridge_Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Ingredient_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Ingredient_id",
                        to="Recipe_Meal_Planner.ingredients",
                    ),
                ),
                (
                    "Recipe_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Recipe_id",
                        to="Recipe_Meal_Planner.recipes",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecipeOwner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Phone_number", models.IntegerField(max_length=10)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipe_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="recipes",
            name="Person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="Recipe_Meal_Planner.recipeowner",
            ),
        ),
    ]
