# Generated by Django 6.0.5 on 2026-05-23 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Recipe_Meal_Planner",
            "0003_remove_ingredients_recipe_alter_recipes_recipe_photo_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe_bridge_table",
            name="Ingredient_calories",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="recipe_bridge_table",
            name="Ingredient_quantity",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="recipe_bridge_table",
            name="Ingredient_unit",
            field=models.CharField(
                max_length=5,
                choices=[("g", "Gram"), ("c", "Cup"), ("p", "Piece")], default="g"
            ),
        ),
        migrations.AddField(
            model_name="recipes",
            name="Ingredients",
            field=models.ManyToManyField(
                through="Recipe_Meal_Planner.Recipe_Bridge_Table",
                to="Recipe_Meal_Planner.ingredients",
            ),
        ),
    ]
