# Generated by Django 6.0.5 on 2026-05-23 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Recipe_Meal_Planner",
            "0004_recipe_bridge_table_ingredient_calories_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe_bridge_table",
            name="Ingredient_unit",
            field=models.CharField(
                max_length=5,
                choices=[("g", "Gram"), ("c", "Cup"), ("p", "Piece")], default="g"
            ),
        ),
    ]
