# Generated by Django 6.0.5 on 2026-05-23 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Recipe_Meal_Planner", "0005_alter_recipe_bridge_table_ingredient_unit"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipe_bridge_table",
            old_name="Ingredient_unit",
            new_name="Ingredient_Unit",
        ),
    ]
