# Generated by Django 6.0.5 on 2026-05-23 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Recipe_Meal_Planner",
            "0006_rename_ingredient_unit_recipe_bridge_table_ingredient_unit",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe_bridge_table",
            name="Ingredient_Unit",
            field=models.CharField(
                choices=[("g", "Gram"), ("c", "Cup"), ("p", "Piece")],
                default="g",
                max_length=2,
            ),
        ),
    ]
