# Generated by Django 6.0.5 on 2026-05-19 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalyzeSave",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("orginal_text", models.TextField()),
                ("updated_text", models.TextField()),
                ("words_count", models.IntegerField()),
                ("sentence_count", models.IntegerField()),
                ("character_count", models.IntegerField()),
                ("paragraph_count", models.IntegerField()),
                ("readablity_score", models.IntegerField()),
                (
                    "User",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
