# Generated by Django 6.0.5 on 2026-05-19 17:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Text_Analyzer", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="analyzesave",
            old_name="User",
            new_name="Person",
        ),
        migrations.AddField(
            model_name="analyzesave",
            name="Saving_date_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="analyzesave",
            name="Title",
            field=models.TextField(default="Title", max_length=100),
            preserve_default=False,
        ),
    ]
