# Generated by Django 6.0.5 on 2026-05-19 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Text_Analyzer", "0002_rename_user_analyzesave_person_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analyzesave",
            name="Saving_date_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
