# Generated by Django 6.0.5 on 2026-05-20 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Text_Analyzer", "0003_alter_analyzesave_saving_date_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="analyzesave",
            name="reading_time",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
