# Generated by Django 6.0.5 on 2026-05-20 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Text_Analyzer", "0004_analyzesave_reading_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analyzesave",
            name="reading_time",
            field=models.FloatField(),
        ),
    ]
